export const GET_BM_NODES_SUCCESS = "GET_BM_NODES_SUCCESS";
export const GET_BM_NODES_ERROR = "GET_BM_NODES_ERROR";
export const APPLY_FILTER = "APPLY_FILTER";
export const SET_STATE = "SET_STATE";
export const ALERT_SUCCESS = "ALERT_SUCCESS";
export const ALERT_ERROR = "ALERT_ERROR";
export const ALERT_CLEAR = "ALERT_CLEAR";
export const COPY_TO_CLIPBOARD = "COPY_TO_CLIPBOARD";
export const CUT_TO_CLIPBOARD = "CUT_TO_CLIPBOARD";
export const SET_SELECTED = "SET_SELECTED";
export const APPEND_SELECTED = "APPEND_SELECTED";
export const REMOVE_SELECTED = "REMOVE_SELECTED";
export const CLEAR_SELECTED = "CLEAR_SELECTED";
export const TOGGLE_SELECTED = "TOGGLE_SELECTED";
export const SET_SELECTED_PIVOT = "SET_SELECTED_PIVOT";
export const SELECT_RANGE_BY_PIVOT = "SELECT_RANGE_BY_PIVOT";

export default {
  GET_BM_NODES_ERROR,
  GET_BM_NODES_SUCCESS,
  APPLY_FILTER,
  SET_STATE,
  ALERT_SUCCESS,
  ALERT_ERROR,
  ALERT_CLEAR,
  COPY_TO_CLIPBOARD,
  CUT_TO_CLIPBOARD,
  SET_SELECTED,
  SET_SELECTED_PIVOT,
  SELECT_RANGE_BY_PIVOT,
  APPEND_SELECTED,
  REMOVE_SELECTED,
  CLEAR_SELECTED,
  TOGGLE_SELECTED
};
