export const GET_BM_NODES_SUCCESS = "GET_BM_NODES_SUCCESS";
export const GET_BM_NODES_ERROR = "GET_BM_NODES_ERROR";
export const APPLY_FILTER = "APPLY_FILTER";
export const SET_STATE = "SET_STATE";

export default {
  GET_BM_NODES_ERROR,
  GET_BM_NODES_SUCCESS,
  APPLY_FILTER,
  SET_STATE
};
