export const GET_BM_NODES_SUCCESS = "GET_BM_NODES_SUCCESS";
export const GET_BM_NODES_ERROR = "GET_BM_NODES_ERROR";
export const APPLY_FILTER = "APPLY_FILTER";
export const SET_STATE = "SET_STATE";
export const ALERT_SUCCESS = "ALERT_SUCCESS";
export const ALERT_ERROR = "ALERT_ERROR";
export const ALERT_CLEAR = "ALERT_CLEAR";

export default {
  GET_BM_NODES_ERROR,
  GET_BM_NODES_SUCCESS,
  APPLY_FILTER,
  SET_STATE,
  ALERT_SUCCESS,
  ALERT_ERROR,
  ALERT_CLEAR
};
